### ISSUE TITLE
NTT_HALS

### ISSUE THREAD

**Issue by WHowbeen** [krzysiekfonal/NHTD_FNTD#1]
Hi krzysiekfonal,

I notice the NTT_HASL.m is not finished, do you have the original version of this code? 

This should be the nonnegative tensor train based on hierarchical ALS.

Thanks.

**Comment by krzysiekfonal** [comment]
Hi @WHowbeen,

It was actually not implemented in this project at all - at the end this project is only about Tucker Decomposition.

However, I've implemented Nonnegative Tensor Train in another project. Ping me on krzysiekfonal@gmail.com if your are interested, I'd love to help.

**Comment by krzysiekfonal** [comment]
Or actually you can find tt-decomposition and projection there - it use underneath lrmf to decompose so you can use any decomposition there (svd or nonnegative like als)

**Comment by WHowbeen** [comment]
Thank you so much for your answer @krzysiekfonal, so glad that you could help!

In fact I was trying to reproduce the NTT using HALS. I just checked the lrmf.m (is it low-rank matrix factorisation if I am not mistaken) and saw nmf_hals being used there. It's nice to know that Tensor Train decomposition can be calculated this efficiently.

Let me try it first. Many thanks!

Haobin
